language: C

compiler:
  - gcc

env:
  - GCC_VERSION=4.6 FC=gfortran-${GCC_VERSION}
  - GCC_VERSION=4.7 FC=gfortran-${GCC_VERSION}
  - GCC_VERSION=4.8 FC=gfortran-${GCC_VERSION}
  - GCC_VERSION=4.9 FC=gfortran-${GCC_VERSION}

before_install:
  - ./travis/before_install.sh

script:
  - cmake . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=yes
  - make
  - make test
