language: C

compiler:
  - gcc

env:
  - GCC_VERSION=4.6
  - GCC_VERSION=4.7
  - GCC_VERSION=4.8
  - GCC_VERSION=4.9

before_install:
  - sudo ./travis/before_install.sh

script:
  - cmake . -DCMAKE_Fortran_COMPILER=gfortran-${GCC_VERSION} -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=yes
  - make
  - make test
