language: C

compiler:
  - gcc

env:
  matrix:
    - gcc:
      - GCC_VERSION=4.6 FC=gfortran-${GCC_VERSION}
      - GCC_VERSION=4.7 FC=gfortran-${GCC_VERSION}
      - GCC_VERSION=4.8 FC=gfortran-${GCC_VERSION}
      - GCC_VERSION=4.9 FC=gfortran-${GCC_VERSION}
    - build_type
      - CMAKE_BUILD_TYPE=Debug
      - CMAKE_BUILD_TYPE=Release

before_install:
  - ./travis/before_install.sh

script:
  - cmake . -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_VERBOSE_MAKEFILE=yes
  - make
  - make test
