gems:
  - jekyll-mentions
  - jekyll-sitemap

footer-links:
  github: nicolasbock

pages_list:
  Main: "/spammpack/"
  Building: "/spammpack/building.html"
  References: "/spammpack/references.html"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

url: http://www.freeon.org/spammpack
baseurl: "/spammpack"
