gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll/scholar

footer-links:
  github: nicolasbock

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Rakefile'
  - 'README.markdown'

pages_list:
  Main: "/spammpack/"
  Building: "/spammpack/building.html"
  References: "/spammpack/references.html"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

scholar:
  style: american-physics-society

url: http://www.freeon.org/spammpack
baseurl: "/spammpack"
