gems:
  - jekyll-mentions

footer-links:
  github: nicolasbock

pages_list:
  Main: "/spammpack/"
  Building: "/spammpack/building.html"
  References: "/spammpack/references.html"

baseurl: "/spammpack"
