#include "config_fortran.h"

MODULE SpAMMPACK_OMP

  USE, INTRINSIC :: iso_C_binding

  IMPLICIT NONE

  INTERFACE SpAMM_OMP_INIT
    SUBROUTINE SpAMM_OMP_INIT ()
      BIND(C, name = "spamm_omp_init")
    END SUBROUTINE SpAMM_OMP_INIT
  END INTERFACE SpAMM_OMP_INIT

END MODULE SpAMMPACK_OMP
