BUILT_SOURCES = $(foreach i, $(INTERFACE_FILES), $(basename $i).decl.h $(basename $i).def.h)
CLEANFILES = $(BUILT_SOURCES) charmrun

%.decl.h %.def.h : %.ci
	$(AM_V_CXX)$(CHARMC) $<

AM_LDFLAGS = -Xcompiler "-language charm++"
